apiVersion: v1
kind: Secret
metadata:
    name: checkout-db
    namespace: checkout
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:16Ah4fwp/MMXI2C8wPKCIIVoC8Rc0SEtTxU=,iv:gmkcvfjSia4mp9EMx5Co1JzGNpBHc6kiiMHHyRWkTX8=,tag:TWoSI81ZM6Hsuoh8zro9vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVlRZdXhiNDlCN3Rwck4v
            OTI1bTVnWldzd3I4bmE1a0RZSStVaGpHbHg0CjBqL3VaQ1NXY2U1TGZJWnhZUWRh
            ZjZaeTkrWGpxcUZCMkM1K21ST2p3ZEUKLS0tIE9JWjk5RzhwVkljU0tmaDZTUTRz
            bmszNXpTMlJnUlZJMmVzbkdwSzhoUW8KQ/3CBYNJ7/SbKp/+tt6Iugsb2UL2lPO2
            QZd4LEfYm5Sc1ZmvdrCqCYHZbS2XXWbTHddwknT3xcOPcOgZ5lBRTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zdyunkzhjehyttuzp9qz8zqdd887l7ga57ysk8g6ngupazh23vsdf4vmp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T12:30:49Z"
    mac: ENC[AES256_GCM,data:Qt3fyREHG9HBxLyewyinkAieA1WzrO24kvbtPtlINijqAaa5wIX+KvIva6GlKxyhlFLnL35LnJ8LjYtGqwwqMSwFjAFu/WyxCWEIirVZCxUBlOZkxW2RfOHYxDoe153W2ZFgVmf0elcQ5gbFIyee8sK4wSoYabkQma7TIt15NXA=,iv:pFIp7G2PkqLCFAP3/ooZdy5udfk4jaYDUuxLNH/ygcg=,tag:j/bGk0TpfbuGKKks55myIA==,type:str]
    version: 3.13.3
