apiVersion: v1
kind: Secret
metadata:
    name: checkout-db
    namespace: checkout
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:NL/1cW1+96ldHlIXxJOmKs6WHaXHZEVYQl4=,iv:J46iSXcLKTjvIvw0oeL8nbxoQvDlU/YfBv8Hko4JuJE=,tag:f8iC+TYoE4UXvaZW4cv8Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcjRSekNtYWh5dlQ4Nmp4
            Zys2dGpuZkhaZkhaYUk1MjVVY2lBb1JESFFrCjB6dVd4am91M2wzVkVzNHRVclNh
            V1hnT0FoOGREdDBNU3BmMnhDN3NNQkkKLS0tIGV4Mmx0eExPSHR3VWEyOEUvVkhw
            MzJWL0xUVWJTNHRUM3dHSjlzTmdSUUEKl8EghJqu0+P8iE5scGwA1Q1yXS3qjUUd
            S+EHaMHKMhPcsFeocPzEDYXlg519PxrpEViBPpaz/XLio1KY5efcXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5d2nza98zcgeq8d9jj28ela3zxpyttwn4srh23jd5du7krepjsg7qas5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T03:55:34Z"
    mac: ENC[AES256_GCM,data:UyfKUX/4E39eI0alpAGuRLhIxSNUMt6RSRHvUu/UmvboIQKgZbixWC4ZOLPYqmQrZNWBAEuAYJ0CVGki8oP58+1o+Iu+OOmwUcmvYvwEOvR9eH1R9HMPrNul0nGf1k5GMr8fo4nHAHE/uO70lcTq1mnUkZGJp1iHKIzoHufRWSg=,iv:L3xONbLzDW2ujSIMMLOyT7Sp3LVk1DqP1EBAY5yeL4A=,tag:2ygyBeSNLAP6nMlD80jLdw==,type:str]
    version: 3.13.3
