---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: checkout-db
  namespace: checkout
spec:
  encryptedData:
    password: AgBxdYy602M9UZfHavxWU0WGeMm7vNmwTWUYKpIcrFFjzbKBN/hcCEVOeg0F/VUDWt7wWrEwTbHcofkXy/YMF5kRDgrbRRdZuM4FBNsscFbGJurMnIA8DxUI+yulapOFNQCtDAbqOKDwrT3elkeBakbQmAZgxCH2I2M/tKRLXDfCSPhWylEtZCC/OJrK0pPL+fFKf/FHkSKdVBoWEsrsc+D9GaTII2M038R/w7i/xrx3DMhN8t+ZMNjmbwYz9cZ43WWDVU/5TbSYt/QdDcxXuPehiQZX6efBfmOjn+SCTsk95DT3sd221ApUhh8UpYptnowh18lbJ7z0A6Lw2l/tZROHwYEV34u2a143AEUT0/5VqCXL+IFaqhwj8IYLkIcgarkG3QgRxQjB0ucASndUKsUpn9Kf7iay94arpqaPl2YEbG0nNEZRIzl1Rf0M94Hqwmf6yVfGe7FjvpydRQIclBXrrE+1HJ15U5yECWpI/UMS0CjzFUeKTzGqjM3gBrtxFcKGHBWsSmw67FUfUHVrgPox9KZGAcrDew+bXq5bmLiREghzElUMeUqLWzMwom+RUXoW08MR9zU4AoQC9HpERhwMFPVfPVsYrOhpd/1dZWsDWT2atmfdl0N067xEMxGSrXCW3jSHcpFO3UbMwHfDIjEkKevZzQJ51oLpDGMr/pOzf02cMJ7RI/e3Hr8yBWfrrJQiSKjEAae/qNMXCx26XB31XUWuPjBD0fLWlA==
  template:
    metadata:
      name: checkout-db
      namespace: checkout
    type: Opaque
