---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: checkout-db
  namespace: checkout
spec:
  encryptedData:
    password: AgDTMIwyQhKniEpuGrWPgxgGrknaTfa2ZXljugVwce/7Q41G8ufMwZ4Mr31nwQH5hFii+zKwUT0E/AxKiGixcdrTTkFfIbdp/Y/6cXjxwf/0sEzESkZipkRFyGC6vWpTv9DMF/lm0ygfUmDrNfCDSPTNMRQxi7K6AGJMD0XGJqITc2R6BQGhCG4XD+5DzOdlJs9dQKL1TlABzu+vsW19nnla9uJHylfBCQGWsR0UFCRtUuz90yduVWk5eV5p9JqJOWhN3kMc+rDUHbYAwpc+WxHXJCEsfut8A5HzrhcavtX/NiYlX8Kv2F1RpzOmKc6JajEIAWF1m5rsSzpotn+o+j1S80pIxWOupBbUifuOl9Rg4jOd6FGyeghkJsagKAolWki1OoIf2woCwfgQyg744bE8P8ehCQoBY2OSQeeJKzgPKZFuSma9VqavlhHnAGaNPiia2VcpZOZN2pUyXGtcQVXRcHmyJRzRvsGHUP6Spqs1l+GOxjuHm89oZhUrdBT1wY3wsBMi4rV+sf8iJlaQbRoSta9FGKg4IqC+2ovL67jnlE34HeY3f1rnMr6nGlZM9npxLbVCzdgkpsGcEgRVVQNk7bUYSe5SjW9Y7ww8BvTB1HOvFsUKU65Z7sNWTURNd2PFJ/pK9LIzHev0YZpBDp5+FlWQBkDj+oCInGu97DspousyG2B7RQe8hGBMQCZaydY00utNvpkROwLyLWnpcUT3LDLYky4W9Yv33A==
  template:
    metadata:
      name: checkout-db
      namespace: checkout
    type: Opaque
