---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: checkout-db
  namespace: checkout
spec:
  encryptedData:
    password: AgDYouJBUxXmITxwBouijQlBBFqkfZ+cHMspYS7+XfEe/jv1n9qoIDzb545QCFbTMQwdq1Y2A3SJI9uDg0RQuO1xO81n7We46q5qa5G9FcjXPv/3x5gR8UU0sjo+IdYahNs7k2S1gpkLilA41Dtnn2HFV5Ig1RYz38EKAnce3QPSjyImDV0Wlqw9QcWYaVG2X5oWHWCDhUGqHHk6/gfGj2UfI0v0EYI7mAdG9zNKpnJ0c/0z8OWFE4SN3gM0TeMUDyGLix7Sk3i/4SX3sqaBuoGeOfWbJS1uPI1x9vsvpKMXMYjzwWm+qxbDTjBPE+76ooNakNlUwzwtpoGp806u5AY/TL1TaTNByGTEMzbkTJv8k9v2A7UGRI8PUOYqN58LoXwqD4aOX/Cbd+k/YhFFQc2wRTxqOIAWp76eu+j5ZHuwNj+nkaY6TQCGYnD/q57dU7zMO5aARBe3TPNFgCOlMfpDHWnfUJRHsm6wqH1go2AWoKPIjBCh7hqLP8x7lXEw0joz0kzcPLXcSnmCbFKd/3pBg+1xE6oNcbJhl8wU76xjYkA3SdttxLLweW6T5RTl1dZ0gDQhxoEfP5kAQLcQzTIw1S+G0tUi6y0/QX2eVBJm90/WjDAh9plIt9yKXW5D8EKXKLZgVta2O2/jGwNqoSDZQkqihMLYRqqbJNAtDTbqG3L8NVR2ZfsYI+/ABLGO0B9QTGx3S7GkxZlJCqhOcwsZ58S/fOEglgT20Q==
  template:
    metadata:
      name: checkout-db
      namespace: checkout
    type: Opaque
