apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: checkout-dev
resources:
  - ../../base
images:
  - name: hashicorp/http-echo
    newTag: "1.0"
replicas:
  - name: checkout
    count: 1
configMapGenerator:
  - name: checkout-banner
    behavior: merge
    literals:
      - banner=checkout v1 — dev
