apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: storefront
spec:
  template:
    metadata:
      annotations:
        rollouts.northwind.io/banner-revision: "v2-attempt-1"
  strategy:
    canary: null
    blueGreen:
      activeService: storefront
      previewService: storefront-preview
      autoPromotionEnabled: false