apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: storefront
spec:
  template:
    metadata:
      annotations:
        rollouts.northwind.io/banner-revision: "v4-analysis-pass"
  strategy:
    canary:
      stableService: storefront
      canaryService: storefront-preview
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: storefront
            namespace: storefront-canary
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: storefront-banner-matches
            args:
              - name: expected-banner
                value: "storefront v4: canary"
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100