apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app.kubernetes.io/name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments
    spec:
      containers:
        - name: payments
          image: hashicorp/http-echo:1.0
          args:
            - "-listen=:5678"
            - "-text=$(BANNER)"
          env:
            - name: BANNER
              valueFrom:
                configMapKeyRef:
                  name: payments-banner
                  key: banner
          ports:
            - name: http
              containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 32Mi
